-- USE TEST;
SELECT NAME FROM users;
SELECT * FROM users WHERE NAME LIKE 'D%';

SELECT * FROM users ORDER BY ID LIMIT 4;
SELECT * FROM USERS ORDER BY ID LIMIT 4 OFFSET 3;
SELECT * FROM users ORDER BY ID LIMIT 3,4;
