USE TEST;
CREATE TABLE if NOT EXISTS address( 
ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT,
STREET VARCHAR(255),
CITY VARCHAR(255),
STATE VARCHAR(50),
PINCODE VARCHAR(10),
CONSTRAINT FK_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE);
DROP TABLE ADDRESS;