-- USE TEST;
/* NOTE:- WHEN CREATE PROCEDURE , DELIMITER IS ANYTHING FOR EX DELIMITER @, 
DELIMITER $$, DELIMITER VINAY
*/
-- SELECT * FROM users;



-- ----------  1. THIS WITHOUT INPUT PROCEDURE --------------
DELIMITER @
CREATE PROCEDURE SELECT_USERS()
BEGIN 
	SELECT * FROM USERS;
END @
DELIMITER ;
-- -- CALL THE PROCEDURE
CALL SELECT_USERS();
DROP PROCEDURE IF EXISTS SELECT_USERS; -- DROP THE SELECT_USERS PROCEDURE 




-- ---------- 2.THIS WITH INPUT PROCEDURE --------------
DELIMITER $$
CREATE PROCEDURE AddUser(
IN U_NAME VARCHAR(30),
IN U_EMAIL VARCHAR(30),
IN u_GENDER ENUM('MALE','FEMALE','OTHER')
)
BEGIN
INSERT INTO users(NAME,EMAIL,GENDER) VALUES (U_NAME,U_EMAIL,U_GENDER);
SELECT * FROM users;
END $$
DELIMITER ;

CALL AddUser('JOLLY2','JOLLY2@VINAY.COM','FEMALE');
DROP PROCEDURE IF EXISTS AddUser; -- DROP AddUser PROCEDURE




-- ------------ 3. CREATE DELETE PROCEDURE WITH INPUT -------------- 
DELIMITER @@
CREATE PROCEDURE DeleteUser(IN U_ID INT)
BEGIN
DELETE FROM USERS WHERE ID = U_ID;
END @@

DELIMITER ;
CALL DeleteUser(27);
DROP PROCEDURE IF EXISTS DeleteUser; -- DROP DeleteUser PROCEDURE
 
-- SHOW ALL PROCEDURES THAT CREATE IN YOUR TABLE 
SHOW PROCEDURE STATUS WHERE DB = 'TEST';

