-- ALTER TABLE USERS ADD COLUMN REFERRED_BY_ID INT;
-- UPDATE USERS SET REFERRED_BY_ID = 1 WHERE ID IN(2,3,13,14,15,16,18,20);
-- UPDATE USERS SET REFERRED_BY_ID = 3 WHERE ID = 2;
SELECT A.ID AS ID, A.NAME AS USER_NAME,
B.NAME AS REFERRED_BY_NAME
FROM USERS A INNER JOIN USERS B ON A.REFERRED_BY_ID = B.ID;
 
SELECT A.ID AS ID, A.NAME AS USER_NAME,
B.NAME AS REFERRED_BY_NAME
FROM USERS A LEFT JOIN USERS B ON A.REFERRED_BY_ID = B.ID;
 
select * from USERS;