USE test;
-- SELECT AVG(SALARY) FROM USERS;
-- SELECT * FROM USERS WHERE SALARY > (SELECT AVG(SALARY) FROM USERS);
-- SELECT * FROM USERS WHERE SALARY < (SELECT AVG(SALARY) FROM USERS);

-- SELECT ID, NAME, REFERRED_BY_ID
-- FROM USERS
-- WHERE REFERRED_BY_ID IN 
-- (SELECT ID FROM USERS WHERE SALARY > 50000);
SELECT ID, NAME, REFERRED_BY_ID
FROM USERS
WHERE REFERRED_BY_ID IN 
(SELECT ID FROM USERS WHERE SALARY < (SELECT AVG(SALARY) FROM users));
SELECT * FROM USERS;
 
