create database test
USE test;
create table users(
id INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) UNIQUE NOT NULL,
GENDER ENUM('MALE','FEMALE','OTHER'),
DATE_OF_BIRTH DATE,
ADDRESS VARCHAR(100) NOT NULL,
CRETAE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
RENAME TABLE CUSTOMERS TO USER;
ALTER TABLE USER ADD COLUMN PAYMENT BOOLEAN DEFAULT TRUE;
ALTER TABLE USER DROP COLUMN PAYMENT;
ALTER TABLE USER MODIFY NAME VARCHAR(50);

ALTER TABLE USER MODIFY COLUMN DATE_OF_BIRTH DATE AFTER EMAIL;

	SELECT * FROM USER; 