USE TEST;
-- RENAME TABLE USER TO USERS;

-- UPDATE USER SET NAME = 'Aarav' WHERE ID = 1;
-- SELECT * FROM USER WHERE SALARY <=60000;
UPDATE USERS SET salary=salary+10000 WHERE salary < 60000;
-- SELECT * FROM USERS WHERE NAME = 'Aarav';
ALTER TABLE USERS ADD COLUMN USERNAME VARCHAR(30);
UPDATE USERS SET USERNAME = 'RAJ_12' WHERE ID = 3;
ALTER TABLE USERS ADD CONSTRAINT unique_username unique (username);
ALTER TABLE USERS DROP INDEX UNIQUE_EMAIL;
ALTER TABLE users MODIFY COLUMN USERNAME VARCHAR(30) NOT NULL;
ALTER TABLE users ADD CONSTRAINT CK_DOB CHECK (DATE_OF_BIRTH > '1925-01-01');
INSERT INTO users (NAME,EMAIL,GENDER,DATE_OF_BIRTH,SALARY) VALUES ('AARAV3','aarav@example3.com','MALE','1920-01-01',65000);
SELECT * FROM users;
-- SET SQL_SAFE_UPDATES = 0;

ALTER USER 'root'@'localhost' IDENTIFIED BY '';
FLUSH PRIVILEGES;
DROP TABLE ADDRESS;
DROP TABLE USERS;