RENAME TABLE CUSTOMERS TO USER
USE TEST;
INSERT INTO USER VALUES
(1,'JOHN DOE','JOHNDOE21@GMAIL.COM','1900-07-13','MALE','ABC NAGAR',DEFAULT),
(2,'JOHN DOE2','JOHNDOE22@GMAIL.COM','1901-07-14','MALE','DEF NAGAR',DEFAULT),
INSERT INTO USER VALUES(3,'JOHN DOE3','JOHNDOE23@GMAIL.COM','1901-07-14','MALE','DEF NAGAR',DEFAULT);

INSERT INTO USER(ID, NAME , EMAIL,GENDER, ADDRESS) VALUES
(4,'VINAY','VINAY@VINAYKHATRI.COM','MALE','ABC');

INSERT INTO USER(ID , EMAIL,GENDER, ADDRESS) VALUES
(5,'VINAY2@VINAYKHATRI.COM','MALE','ABC');

SELECT * FROM USER;