USE TEST;

CREATE TABLE USER_LOG(
ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT,
USER_NAME VARCHAR(40),
CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER $$

CREATE TRIGGER AFTER_USER_INSERT
AFTER INSERT ON users
FOR EACH ROW 
BEGIN 
INSERT INTO USER_LOG(USER_ID,USER_NAME) VALUES (NEW.ID,NEW.NAME);

END $$

DELIMITER ;

DROP TRIGGER if exists after_user_insert;

INSERT INTO users(name,EMAIL,GENDER,SALARY) VALUES
 ('JOLLY','JOLLY@gmail.com','FEMALE',40000);
SELECT * FROM users;

SELECT * FROM USER_LOG;
 
