USE TEST;

CREATE VIEW USERS_TB AS 
SELECT * FROM users WHERE SALARY > 70000;

DROP VIEW USERS_TB;

UPDATE users SET SALARY = 84000 WHERE ID = 6;

SELECT NAME,EMAIL,SALARY FROM USERS_TB;
SELECT * FROM users;